name: Daily Stock Report

on:
  schedule:
    - cron: '15 13 * * *'  # Runs every day at 1:15 PM UTC
  workflow_dispatch:        # Allows manual triggering from the GitHub UI

jobs:
  send-report:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock report script
        run: python main.py
